language: node_js
node_js:
- "node"
before_install:
- npm config set spin false
- npm i -g makeshift && makeshift -r https://registry.npmjs.org
install:
- yarn
script:
- |
  if [ -n "$TRAVIS_TAG" ]; then
    npm run build
  fi
- |
  if [ "$TRAVIS_PULL_REQUEST" = "true" ]; then
    bash npm run test
  fi
deploy:
  - provider: npm
    skip_cleanup: true
    email: kchau@microsoft.com
    api_key: BAD_TOKEN
    tag: latest
    on:
      tags: true
      all_branches: true
      condition: $TRAVIS_TAG != *-*
  - provider: npm
    skip_cleanup: true
    email: kchau@microsoft.com
    api_key: BAD_TOKEN
    tag: next
    on:
      tags: true
